<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Comment
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Comment extends EntityRepository
{
    /**
     * Save comment object.
     * @param \AppBundle\Entity\Comment $comment
     * @param
     */
    public function save(\Appbundle\Entity\Comment $comment)
    {
        $this->_em->persist($comment);
        $this->_em->flush();
    }

    /**
     * Delete answer object.
     *
     * @param Comment $comment Comment object
     *
     * @return mixed
     */
    public function delete(\AppBundle\Entity\Comment $comment)
    {
        if (!$comment) {
            throw $this->createNotFoundException('No comment found');
        }
        $this->_em->remove($comment);
        $this->_em->flush();
    }

}
